apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbt-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aymen-bacha/projet_test.git'
    targetRevision: main
    path: gitops 
  destination:
    server: https://kubernetes.default.svc
    namespace: dbt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

